"""Recalibration of `v1`'s components and xP (PLAN §5 *Calibration*; Phase 5 plan,
*Calibration* and Task 5).

**What is recalibrated** (each only if it improved develop metrics, `dev/calibrate_v1.py`):
- isotonic maps of P(start), the team's P(clean sheet) and P(goal ≥ 1) per player-fixture;
- a per-position linear map of the per-fixture xP: xp' = a · p_play + b · xp (the intercept
  scales with P(plays), so a player who will not play keeps xP 0, and a blank stays 0).

**Isotonic** (`isotonic`): weighted pool-adjacent-violators on the predictions sorted
ascending, after pooling them into at most `MAX_BINS` consecutive equal-count bins (their
weighted mean prediction and outcome), so a map has a few hundred breakpoints at most. The
map (`Isotonic.apply`) interpolates linearly between the blocks' mean predictions and is
flat beyond the first and last; a prediction of exactly 0 stays 0 (bans, players ruled out,
no team λ: the zeros are rules, not estimates). Separate maps per horizon group are allowed
(`Calibration` holds (first horizon, map) pairs).

**Leak-free by construction (PLAN §4):** a calibration fitted on all of develop and applied
to develop would put later seasons' outcomes into earlier predictions. The maps are fitted
on an expanding window instead: the calibration applied in season S is fitted on the
walk-forward predictions and outcomes of the seasons before S only
(`fplopt.models.calibration_table`, generated by `dev/calibrate_v1.py`, one entry per
season: "fit on seasons < S"). A season before the first entry is uncalibrated; a season
after the last entry uses the last one (fitted on 2016/17–2024/25: the holdout and live
seasons). The table holds plain tuples; `calibration_for(season)` builds the frozen
`Calibration` from them. No state, no file access.
"""

from __future__ import annotations

from dataclasses import dataclass

import numpy as np

from fplopt.models.calibration_table import CALIBRATION_TABLE

__all__ = (
    "MAX_BINS",
    "Calibration",
    "Isotonic",
    "apply_isotonic",
    "calibration_for",
    "from_table",
    "isotonic",
    "linear_by_position",
    "to_table",
)

MAX_BINS = 200
DIGITS = 6  # breakpoints are rounded to this many decimals in the table


@dataclass(frozen=True)
class Isotonic:
    """A non-decreasing map given by breakpoints (x ascending, y non-decreasing)."""

    x: tuple[float, ...]
    y: tuple[float, ...]

    def apply(self, values: np.ndarray) -> np.ndarray:
        values = np.asarray(values, dtype="float64")
        if not self.x:
            return values.copy()
        mapped = np.interp(values, np.asarray(self.x), np.asarray(self.y))
        return np.where(values > 0, mapped, values)


def _pav(y: np.ndarray, w: np.ndarray) -> np.ndarray:
    """Weighted pool-adjacent-violators: the non-decreasing fit of y (in order) per point."""
    means, weights, sizes = [], [], []
    for value, weight in zip(y.tolist(), w.tolist(), strict=True):
        means.append(value)
        weights.append(weight)
        sizes.append(1)
        while len(means) > 1 and means[-2] > means[-1]:
            total = weights[-2] + weights[-1]
            merged = (means[-2] * weights[-2] + means[-1] * weights[-1]) / total
            means[-2:] = [merged]
            weights[-2:] = [total]
            sizes[-2:] = [sizes[-2] + sizes[-1]]
    return np.repeat(np.asarray(means), np.asarray(sizes))


def isotonic(
    pred: np.ndarray, outcome: np.ndarray, weight: np.ndarray | None = None, bins: int = MAX_BINS
) -> Isotonic:
    """The isotonic map of `outcome` on `pred` (module docstring). Rows with pred ≤ 0 or a
    non-finite value are left out (zeros are never mapped)."""
    pred = np.asarray(pred, dtype="float64")
    outcome = np.asarray(outcome, dtype="float64")
    weight = np.ones_like(pred) if weight is None else np.asarray(weight, dtype="float64")
    keep = (pred > 0) & np.isfinite(pred) & np.isfinite(outcome) & (weight > 0)
    pred, outcome, weight = pred[keep], outcome[keep], weight[keep]
    if not len(pred):
        return Isotonic((), ())
    order = np.argsort(pred, kind="mergesort")
    pred, outcome, weight = pred[order], outcome[order], weight[order]
    edges = np.unique(np.linspace(0, len(pred), min(bins, len(pred)) + 1).astype("int64"))
    codes = np.searchsorted(edges, np.arange(len(pred)), side="right") - 1
    w = np.bincount(codes, weights=weight)
    x = np.bincount(codes, weights=weight * pred) / w
    y = np.bincount(codes, weights=weight * outcome) / w
    fitted = _pav(y, w)
    # One breakpoint per PAV block: its weighted mean prediction and fitted value.
    block = np.concatenate([[0], np.cumsum(np.diff(fitted) != 0)])
    bw = np.bincount(block, weights=w)
    bx = np.bincount(block, weights=w * x) / bw
    by = np.bincount(block, weights=w * fitted) / bw
    return Isotonic(
        tuple(round(float(v), DIGITS) for v in bx), tuple(round(float(v), DIGITS) for v in by)
    )


def linear_by_position(
    element_type: np.ndarray,
    p_play: np.ndarray,
    xp: np.ndarray,
    points: np.ndarray,
    weight: np.ndarray | None = None,
) -> tuple[tuple[int, float, float], ...]:
    """Per position (element_type, a, b) of the weighted least-squares fit points ≈ a ·
    p_play + b · xp (no other intercept); positions without rows are left out."""
    element_type = np.asarray(element_type)
    weight = np.ones(len(element_type)) if weight is None else np.asarray(weight, dtype="float64")
    out = []
    for position in sorted(set(element_type.tolist())):
        rows = element_type == position
        x = np.column_stack([np.asarray(p_play)[rows], np.asarray(xp)[rows]]).astype("float64")
        w = weight[rows]
        gram = x.T @ (x * w[:, None])
        if abs(np.linalg.det(gram)) < 1e-12:
            continue
        a, b = np.linalg.solve(gram, x.T @ (w * np.asarray(points, dtype="float64")[rows]))
        out.append((int(position), round(float(a), DIGITS), round(float(b), DIGITS)))
    return tuple(out)


@dataclass(frozen=True)
class Calibration:
    """The maps applied in one season; None = that part is not recalibrated. Isotonic
    parts are ((first horizon, map), ...), ascending: a row uses the last pair whose first
    horizon is ≤ its horizon. `xp`: (element_type, a, b) per position."""

    fitted_on: tuple[int, ...]
    p_start: tuple[tuple[int, Isotonic], ...] | None = None
    p_cs: tuple[tuple[int, Isotonic], ...] | None = None
    p_goal: tuple[tuple[int, Isotonic], ...] | None = None
    xp: tuple[tuple[int, float, float], ...] | None = None


def apply_isotonic(
    maps: tuple[tuple[int, Isotonic], ...], values: np.ndarray, horizon: np.ndarray
) -> np.ndarray:
    """`values` mapped per row by the map of its horizon group."""
    out = np.asarray(values, dtype="float64").copy()
    horizon = np.asarray(horizon)
    for i, (first, curve) in enumerate(maps):
        last = maps[i + 1][0] if i + 1 < len(maps) else np.inf
        rows = (horizon >= first) & (horizon < last)
        out[rows] = curve.apply(out[rows])
    return out


ISOTONIC_PARTS = ("p_start", "p_cs", "p_goal")


def to_table(calibration: Calibration) -> tuple:
    """The plain-tuple form stored in `calibration_table` (inverse of `from_table`)."""
    parts = [("fitted_on", calibration.fitted_on)]
    for name in ISOTONIC_PARTS:
        maps = _part(calibration, name)
        if maps is not None:
            parts.append((name, tuple((first, curve.x, curve.y) for first, curve in maps)))
    if calibration.xp is not None:
        parts.append(("xp", calibration.xp))
    return tuple(parts)


def _part(calibration: Calibration, name: str) -> tuple | None:
    parts = {"p_start": calibration.p_start, "p_cs": calibration.p_cs}
    return parts.get(name, calibration.p_goal)


def from_table(entry: tuple) -> Calibration:
    """A `Calibration` from its plain-tuple form."""
    values = dict(entry)
    maps = {
        name: tuple((int(first), Isotonic(tuple(x), tuple(y))) for first, x, y in values[name])
        for name in ISOTONIC_PARTS
        if name in values
    }
    return Calibration(
        fitted_on=tuple(values["fitted_on"]),
        p_start=maps.get("p_start"),
        p_cs=maps.get("p_cs"),
        p_goal=maps.get("p_goal"),
        xp=values.get("xp"),
    )


def calibration_for(season: int, table: tuple = CALIBRATION_TABLE) -> Calibration | None:
    """The calibration applied in `season`: the table's entry for it, the last entry for a
    later season, None before the first (module docstring)."""
    if not table:
        return None
    seasons = [int(s) for s, _ in table]
    if season < seasons[0]:
        return None
    index = max(i for i, s in enumerate(seasons) if s <= season)
    return from_table(table[index][1])
